// Function to show hospital details in modal
function showHospitalDetails(hospitalName) {
    const hospital = hospitals.find(h => h.name === hospitalName);
    const modalBody = document.getElementById('hospitalModalBody');
    const modalTitle = document.getElementById('hospitalModalLabel');

    modalTitle.textContent = hospital.name;
    modalBody.innerHTML = `
    <img src="${hospital.image}" class="modal-img" alt="${hospital.name}">
    <div class="mb-4">
        <h5>Description</h5>
        <p class="modal-description">${hospital.description}</p>
    </div>
    <div class="modal-specialties mb-4">
        <h5>Specialties</h5>
        <ul>
            ${hospital.specialties.map(specialty => `<li>${specialty}</li>`).join('')}
        </ul>
    </div>
    <div class="modal-contact mb-4">
        <h5>Contact Information</h5>
        <p>
            <span class="text-muted mb-1 d-block"><i class="fas fa-map-marker-alt icon"></i>${hospital.address}</span>
            <span class="text-muted mb-1 d-block"><i class="fas fa-phone icon"></i><a href="tel:${hospital.phone}" class="text-decoration-none">${hospital.phone}</a></span>
            ${hospital.email ? `<span class="text-muted mb-1 d-block"><i class="fas fa-envelope icon"></i><a href="mailto:${hospital.email}" class="text-decoration-none">${hospital.email}</a></span>` : ''}
            ${hospital.website ? `<span class="text-muted mb-1 d-block"><i class="fas fa-globe icon"></i><a href="${hospital.website}" target="_blank" class="text-decoration-none">${hospital.website}</a></span>` : ''}
        </p>
    </div>
    <div class="modal-timings">
        <i class="far fa-clock icon"></i> ${hospital.timings}
    </div>
    <div class="modal-footer">
        <p class="text-muted">Generated by chintala-sanjay on 2025-03-07 06:57:48 (UTC)</p>
    </div>`;

    hospitalModal.show();
}